package com.DienThoaiGiaRe.entity;
// Generated Dec 24, 2020, 6:46:30 PM by Hibernate Tools 5.4.21.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orders generated by hbm2java
 */

@Entity
@Table(name = "orders")
public class Orders implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1618394727774401949L;
	/**
	 * 
	 */
	@Id
	@Column(name ="id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	
	@Column(name ="amount")
	private double amount;
	
	@Column(name ="customer_address")
	private String customerAddress;
	
	@Column(name ="customer_email")
	private String customerEmail;
	
	@Column(name ="customer_name")
	private String customerName;
	
	@Column(name ="customer_phone")
	private String customerPhone;
	
	@Column(name ="order_date")
	private Date orderDate;
	
	
	@Column(name ="order_num")
	private int orderNum;
	
	public Orders() {
	}

	public Orders(int id, double amount, String customerAddress, String customerEmail, String customerName,
			String customerPhone, Date orderDate, int orderNum) {
		this.id = id;
		this.amount = amount;
		this.customerAddress = customerAddress;
		this.customerEmail = customerEmail;
		this.customerName = customerName;
		this.customerPhone = customerPhone;
		this.orderDate = orderDate;
		this.orderNum = orderNum;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public int getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}

}
