package com.DienThoaiGiaRe.entity;
// Generated Dec 20, 2020, 2:43:06 PM by Hibernate Tools 5.4.21.Final

import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 2115884010592674597L;
	@Id
	@Column(name ="id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	
	@Column(name ="hidden")
	private Boolean hidden;
	
	@Column(name ="id_category", length = 255)
	private int idCategory;
	
	@Column(name ="image")
	private String image;
	
	@Column(name ="image_large")
	private String imageLarge;
	
	@Column(name ="image_thumnail")
	private String imageThumnail;
	
	@Column(name ="inventory")
	private Integer inventory;
	
	@Column(name ="name")
	private String name;
	
	@Column(name ="price")
	private Double price;
	
	@Column(name ="price_dis")
	private Double priceDis;
	
	@Column(name ="weight")
	private String weight;
	
	@Column(name ="specifications")
	private String specifications;
	
	@Column(name ="short_decription")
	private String shortDecription;
	
	@Column(name ="modifieddate")
	private Date modifieddate;
	
	@Column(name ="brand")
	private String brand;
	
	@Column(name ="product_code")
	private String productCode;
	
	public Product() {
	}

	public Product(int id) {
		this.id = id;
	}

	public Product(int id, Boolean hidden, int idCategory, String image, String imageLarge, String imageThumnail,
			Integer inventory, String name, Double price, Double priceDis, String weight, String specifications,
			String shortDecription, Date modifieddate, String brand, String productCode) {
		this.id = id;
		this.hidden = hidden;
		this.idCategory = idCategory;
		this.image = image;
		this.imageLarge = imageLarge;
		this.imageThumnail = imageThumnail;
		this.inventory = inventory;
		this.name = name;
		this.price = price;
		this.priceDis = priceDis;
		this.weight = weight;
		this.specifications = specifications;
		this.shortDecription = shortDecription;
		this.modifieddate = modifieddate;
		this.brand = brand;
		this.productCode = productCode;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Boolean getHidden() {
		return this.hidden;
	}

	public void setHidden(Boolean hidden) {
		this.hidden = hidden;
	}

	public int getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(int idCategory) {
		this.idCategory = idCategory;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getImageLarge() {
		return this.imageLarge;
	}

	public void setImageLarge(String imageLarge) {
		this.imageLarge = imageLarge;
	}

	public String getImageThumnail() {
		return this.imageThumnail;
	}

	public void setImageThumnail(String imageThumnail) {
		this.imageThumnail = imageThumnail;
	}

	public Integer getInventory() {
		return this.inventory;
	}

	public void setInventory(Integer inventory) {
		this.inventory = inventory;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getPriceDis() {
		return this.priceDis;
	}

	public void setPriceDis(Double priceDis) {
		this.priceDis = priceDis;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getDecription() {
		return this.specifications;
	}

	public void setDecription(String specifications) {
		this.specifications = specifications;
	}

	public String getShortDecription() {
		return this.shortDecription;
	}

	public void setShortDecription(String shortDecription) {
		this.shortDecription = shortDecription;
	}

	public Date getModifieddate() {
		return this.modifieddate;
	}

	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	
}
